--[[--------------------------------------------------------------------
	Broker_PlayedTime
	DataBroker plugin to track played time across all your characters.
	Copyright (c) 2010-2016 Phanx <addons@phanx.net>. All rights reserved.
	http://www.wowinterface.com/downloads/info16711-BrokerPlayedTime.html
	https://mods.curse.com/addons/wow/broker-playedtime
	https://github.com/Phanx/Broker_PlayedTime
----------------------------------------------------------------------]]

local ADDON, L = ...

setmetatable(L, { __index = function(t, k)
	local v = tostring(k)
	t[k] = v
	return v
end })

-- THE REST OF THIS FILE IS AUTOMATICALLY GENERATED. SEE:
-- https://wow.curseforge.com/addons/broker-playedtime/localization/

------------------------------------------------------------------------
-- English
------------------------------------------------------------------------

local CURRENT_LOCALE = GetLocale()
if CURRENT_LOCALE == "enUS" then return end

------------------------------------------------------------------------
-- German
------------------------------------------------------------------------

if CURRENT_LOCALE == "deDE" then

L["Played Time"] = "Gespielte Zeit"
L["Right click for settings"] = "Rechtsklick für Einstellungen"
L["Total"] = "Gesamt"
L["Sorting"] = "Sortierung"
L["By played time"] = "Nach Zeit"
L["By played time this level"] = "Nach Zeit auf dieser Stufe"
L["By character name"] = "Nach Charaktername"
L["By character level"] = "Nach Charakterlevel"
L["Sorting of equal levels"] = "Sortierung gleicher Stufen"
L["Show character levels"] = "Charakterlevel anzeigen"
L["Show played time this level"] = "Gespielte Zeit auf dieser Stufe anzeigen"
L["Show class icons"] = "Klassensymbole anzeigen"
L["Show faction icons"] = "Fraktionssymbole anzeigen"
L["None"] = "Keine"
L["Group by factions"] = "Nach Fraktionen gruppiert"
L["Current realm only"] = "Nur aktuelles Realm"
L["Current character on top"] = "Aktueller Charakter oben"
L["Current character highlighted"] = "Aktueller Charakter mit Pfeil"
L["Time in hours (not days)"] = "Zeit in Stunden (nicht Tagen)"
L["Always show minutes also"] = "Immer auch Minuten anzeigen"
L["Remove character"] = "Charakter entfernen"
L["Broker icon text"] = "Broker Icontext"
L["Current character time"] = "Zeit des aktuellen Charakters"
L["Total time"] = "Gesamtzeit"

return end

------------------------------------------------------------------------
-- Spanish
------------------------------------------------------------------------

if CURRENT_LOCALE == "esES" then

L["Show character levels"] = "Niveles de personajes"
L["Show class icons"] = "Iconos de clase"
L["Show faction icons"] = "Iconos de facción"
L["Current realm only"] = "Sólo el reino actual"
L["Remove character"] = "Eliminar personaje"

return end

------------------------------------------------------------------------
-- Latin American Spanish
------------------------------------------------------------------------

if CURRENT_LOCALE == "esMX" then

L["Show character levels"] = "Niveles de personajes"
L["Show class icons"] = "Iconos de clase"
L["Show faction icons"] = "Iconos de facción"
L["Current realm only"] = "Sólo el reino actual"
L["Remove character"] = "Eliminar personaje"

return end

------------------------------------------------------------------------
-- French
------------------------------------------------------------------------

if CURRENT_LOCALE == "frFR" then

L["Show character levels"] = "Niveaux de personnages"
L["Show class icons"] = "Icônes de classe"
L["Show faction icons"] = "Icônes de faction"
L["Current realm only"] = "Royaume actuel uniquement"
L["Remove character"] = "Supprimer personnage"

return end

------------------------------------------------------------------------
-- Italian
------------------------------------------------------------------------

if CURRENT_LOCALE == "itIT" then

L["Show character levels"] = "Livelli di caratteri"
L["Show class icons"] = "Icone di classi"
L["Show faction icons"] = "Icone di fazioni"
L["Current realm only"] = "Solo il reame corrente"
L["Remove character"] = "Rimuovere il carattere"
L["Total"] = "Totale"

return end

------------------------------------------------------------------------
-- Brazilian Portuguese
------------------------------------------------------------------------

if CURRENT_LOCALE == "ptBR" then

L["Show character levels"] = "Níveis de personagem"
L["Show class icons"] = "Ícones da classe"
L["Show faction icons"] = "Ícones da facção"
L["Current realm only"] = "Só o reino atual"
L["Remove character"] = "Remover o personagem"

return end

------------------------------------------------------------------------
-- Russian
------------------------------------------------------------------------

if CURRENT_LOCALE == "ruRU" then

L["Show character levels"] = "Уровни персонажей"
L["Show class icons"] = "Значки классов"
L["Show faction icons"] = "Значки фракций"
L["Remove character"] = "Удалить персонаж"
L["Total"] = "Общее"

return end

------------------------------------------------------------------------
-- Korean
------------------------------------------------------------------------

if CURRENT_LOCALE == "koKR" then

L["Show character levels"] = "캐릭터 레벨"
L["Show class icons"] = "직업 아이콘"
L["Show faction icons"] = "진영 아이콘"
L["Remove character"] = "캐릭터 삭제"
L["Total"] = "전체"

return end

------------------------------------------------------------------------
-- Simplified Chinese
------------------------------------------------------------------------

if CURRENT_LOCALE == "zhCN" then

L["Show character levels"] = "角色等级"
L["Show class icons"] = "职业图标"
L["Show faction icons"] = "阵营图标"
L["Remove character"] = "移除角色"
L["Total"] = "总游戏时间"

return end

------------------------------------------------------------------------
-- Traditional Chinese
------------------------------------------------------------------------

if CURRENT_LOCALE == "zhTW" then

L["Show character levels"] = "角色等級"
L["Show class icons"] = "職業圖示"
L["Show faction icons"] = "陣營圖示"
L["Remove character"] = "移除角色"
L["Total"] = "總遊戲時間"

return end
